- name: install python
  become: yes
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: yes
  with_items:
  - python3
  - python3-doc
  - python3-dev
  - python3-pip
  - python2.7
  - python2.7-doc
  - python2.7-dev
  - python-pip
  - virtualenv
  - virtualenvwrapper
  - virtualenv-clone
  - exuberant-ctags
