- name: install virtualbox
  become: yes
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: yes
  with_items:
  - virtualbox
  - virtualbox-guest-utils
  - virtualbox-guest-dkms
  - virtualbox-guest-x11
