- name: add sublime gpg
  become: yes
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: add sublime repository
  become: true
  apt_repository:
    repo: "deb https://download.sublimetext.com/ apt/stable/"
    state: present

- name: install sublime merge
  become: true
  apt:
    pkg: "sublime-merge"
    state: latest
    update_cache: yes

- name: create full symlink to sublime_merge
  file:
    src: "/opt/sublime_merge/sublime_merge"
    dest: ~/.local/bin/sublime_merge
    state: link

- name: create short symlink to sublime_merge
  file:
    src: "/opt/sublime_merge/sublime_merge"
    dest: ~/.local/bin/sm
    state: link
