- name: install git
  become: yes
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: yes
  with_items:
  - git
  - gitk

- name: apply git config
  copy: src=./.dotfiles/.gitconfig dest=~/.gitconfig

- name: create gitk config directory
  file: path=~/.config/git state=directory

- name: apply gitk config
  copy: src=./.dotfiles/.config/git/gitk dest=~/.config/git/gitk
